import os
from building import *

cwd = GetCurrentDir() # get current dir path

# Add source code
src = Glob('*.c')
inc = [cwd]

if GetDepend('SDK_VERSION_2_5'):
    SrcRemove(src, 'bt_pan.c')
else:
    SrcRemove(src, 'bt_pan_mp3.c')

group = DefineGroup('BT_PAN', src, depend = ['CFG_PAN'], CPPPATH = inc)

Return('group')
