import os
from building import *

cwd = GetCurrentDir() # get current dir path

# Add source code
src = Glob('*.c')
inc = [cwd]
group = DefineGroup('mp3ol', src, depend = [''], CPPPATH = inc)

Return('group')
