from building import *
import rtconfig
import os

src = []
inc = []
cwd = GetCurrentDir() # get current dir path

src+=Glob('*.c')
inc+= [cwd]

#src.extend(SConscript('lv_demos/SConscript', variant_dir="lv_demos", duplicate=0))


#Return('src')

# add lvgl demos
src.extend(SConscript(os.path.join(cwd, 'lv_demos/SConscript'), variant_dir="lv_demos", duplicate=0))


group = DefineGroup('LVGL_DEMO', src, depend = ['PKG_USING_LITTLEVGL2RTT'], CPPPATH = inc)
Return('group')
